parameters:
    cisco.menu.access_verifier.class:  CiscoSystems\MenuBundle\Authorisation\DefaultAccessVerifier
    cisco.twig.menu_extension.class:  CiscoSystems\MenuBundle\Twig\Extension\MenuExtension

services:
    cisco.menu.access_verifier:
        class: '%cisco.menu.access_verifier.class%'
        arguments:
            - '@security.context'
            - '@security.access.decision_manager'
            - '@security.access_map'
            - '@router'
    cisco.twig.menu_extension:
        class: '%cisco.twig.menu_extension.class%'
        arguments:
            - '@cisco.menu.access_verifier'
            - '@twig'
            - '%cisco.menu.config%'
        tags:
            - { name: twig.extension }
