parameters:
    cisco.menu.default_access_verifier.class:  CiscoSystems\MenuBundle\Authorisation\DefaultAccessVerifier
    cisco.twig.menu_extension.class:  CiscoSystems\MenuBundle\Twig\Extension\MenuExtension

services:
    cisco.menu.default_access_verifier:
        class: '%cisco.menu.default_access_verifier.class%'
        arguments:
            - '@security.token_storage'
            - '@security.access.decision_manager'
            - '@security.access_map'
            - '@router'
        tags:
          - { name: cisco.menu.access_verifier, alias: default_menu_access_verifier }
    cisco.twig.menu_extension:
        class: '%cisco.twig.menu_extension.class%'
        arguments:
        # http://richardmiller.co.uk/2012/02/22/symfony2-manipulating-service-parameters-and-definitions/
            - '@cisco.menu.default_access_verifier'
            - '@twig'
            - '%cisco.menu.config%'
        tags:
            - { name: twig.extension }
